plugins {
  id 'java-library'
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  // کتابخانه‌های شبکه و JSON
  implementation "com.squareup.okhttp3:okhttp:4.12.0"
  implementation "com.fasterxml.jackson.core:jackson-databind:2.16.0"

  // --- فقط از این کتابخانه‌ها برای چت استفاده می‌کنیم ---
  implementation 'com.github.NaikSoftware:StompProtocolAndroid:1.6.6'
  implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
  implementation 'com.github.NaikSoftware:ok-http-stomp-connection-provider:1.6.6'

  // وابستگی‌های اصلی LibGDX و پروژه شما
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  implementation project(":shared")
}
allprojects {
  tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
  }
}
