plugins {
  id 'java-library'
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  // کتابخانه‌های شبکه و JSON
  implementation "com.squareup.okhttp3:okhttp:4.12.0"
  implementation "com.fasterxml.jackson.core:jackson-databind:2.16.0"
  implementation 'com.google.code.gson:gson:2.10.1'

  // --- کتابخانه‌های Spring برای کلاینت WebSocket ---
  implementation 'org.springframework:spring-websocket:6.1.10'
  implementation 'org.springframework:spring-messaging:6.1.10'
  implementation 'javax.websocket:javax.websocket-api:1.1'
  implementation 'org.glassfish.tyrus.bundles:tyrus-standalone-client:2.1.5'

  // وابستگی‌های اصلی LibGDX و پروژه شما
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  implementation project(":shared")
}
allprojects {
  tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
  }
}
