[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  implementation "com.squareup.okhttp3:okhttp:4.12.0"
  implementation "com.fasterxml.jackson.core:jackson-databind:2.16.0"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  implementation 'com.google.code.gson:gson:2.10.1'
  implementation project(":shared")
  implementation("com.squareup.okhttp3:okhttp:4.12.0") // latest OkHttp
  implementation("com.google.code.gson:gson:2.10.1")

  if (enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}
allprojects {
  tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
  }
}
